# Site settings
author: Kosta Tzioumis
title: To say nothing of the data
header-img: img/home-bg.png
email: kosta.tzioumis@gmail.com
copyright_name: Kosta Tzioumis
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Data Science Online Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ktzioumis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
